// Deploy mock VNeID server lên VPS
// 1) SFTP upload _ops/mock-vneid/* → /var/www/mock-vneid/
// 2) SSH: npm install --omit=dev, pm2 start (or restart) server.js as "mock-vneid"
// 3) Append nginx location /_vneid/ → 127.0.0.1:3011, reload nginx
// 4) curl healthz để verify

const { Client } = require('ssh2');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const HOST = '45.119.83.233';
const USER = 'root';
const PASS = 'Tailoc@2026';
const REMOTE_DIR = '/var/www/mock-vneid';
const LOCAL_DIR  = path.join(__dirname, 'mock-vneid');

// MITIGATION #2: Gen random secret, write to ecosystem.config.js trước khi upload
const SECRET = crypto.randomBytes(32).toString('hex');
const ECOSYSTEM_CONFIG = `// Auto-generated by deploy_mock_vneid.js — DO NOT edit manually
module.exports = {
  apps: [{
    name: 'mock-vneid',
    script: 'server.js',
    cwd: '${REMOTE_DIR}',
    time: true,
    autorestart: true,
    max_memory_restart: '200M',
    env: {
      NODE_ENV: 'production',
      PORT: 3011,
      MOCK_VNEID_SECRET: '${SECRET}',
      MOCK_VNEID_ISSUER: 'https://anticounterfeit.test9.io.vn/_vneid',
      MOCK_VNEID_PREFIX: '/_vneid',
    },
  }],
};
`;
fs.writeFileSync(path.join(LOCAL_DIR, 'ecosystem.config.js'), ECOSYSTEM_CONFIG, 'utf8');
console.log(`[gen] ecosystem.config.js written, secret=${SECRET.substring(0, 12)}...(${SECRET.length} chars)`);

const FILES_TO_UPLOAD = ['package.json', 'server.js', 'README.md', '.env.example', 'ecosystem.config.js'];

const NGINX_CONF_PATH = '/etc/nginx/sites-available/anticounterfeit.test9.io.vn';
const NGINX_MARKER_BEGIN = '# ── BEGIN mock-vneid (managed) ──';
const NGINX_MARKER_END   = '# ── END mock-vneid (managed) ──';
const NGINX_LOCATION_BLOCK = `
    ${NGINX_MARKER_BEGIN}
    location /_vneid/ {
        proxy_pass http://127.0.0.1:3011/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    ${NGINX_MARKER_END}
`.trim();

function run(conn, cmd) {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, (err, stream) => {
      if (err) return reject(err);
      let stdout = '', stderr = '';
      stream.on('close', (code) => resolve({ code, stdout, stderr }))
        .on('data', d => stdout += d.toString())
        .stderr.on('data', d => stderr += d.toString());
    });
  });
}

async function main() {
  const conn = new Client();
  await new Promise((resolve, reject) => {
    conn.on('ready', resolve).on('error', reject)
      .connect({ host: HOST, port: 22, username: USER, password: PASS, readyTimeout: 10000 });
  });
  console.log('[ssh] connected');

  // 1) mkdir + sftp upload
  await run(conn, `mkdir -p ${REMOTE_DIR}`);
  const sftp = await new Promise((resolve, reject) => conn.sftp((e, s) => e ? reject(e) : resolve(s)));
  for (const f of FILES_TO_UPLOAD) {
    const local = path.join(LOCAL_DIR, f);
    const remote = `${REMOTE_DIR}/${f}`;
    await new Promise((resolve, reject) => sftp.fastPut(local, remote, e => e ? reject(e) : resolve()));
    console.log(`[sftp] uploaded ${f}`);
  }

  // 2) npm install + pm2 start
  console.log('[npm] installing...');
  let r = await run(conn, `cd ${REMOTE_DIR} && npm install --omit=dev --no-audit --no-fund 2>&1 | tail -15`);
  console.log(r.stdout);
  if (r.code !== 0) { console.error('npm install failed:', r.stderr); conn.end(); process.exit(1); }

  console.log('[pm2] start/restart mock-vneid (via ecosystem.config.js)...');
  r = await run(conn, `cd ${REMOTE_DIR} && (pm2 describe mock-vneid >/dev/null 2>&1 && pm2 delete mock-vneid >/dev/null 2>&1 || true) && pm2 start ecosystem.config.js && pm2 save`);
  console.log(r.stdout);

  // 3) nginx config — chỉ thêm 1 lần (idempotent)
  console.log('[nginx] checking config...');
  r = await run(conn, `grep -c '${NGINX_MARKER_BEGIN}' ${NGINX_CONF_PATH} || true`);
  const alreadyHas = parseInt((r.stdout || '0').trim(), 10) > 0;
  if (alreadyHas) {
    console.log('[nginx] mock-vneid block already present, skipping');
  } else {
    // MITIGATION #1: Backup nginx config trước khi sed
    const backupPath = `${NGINX_CONF_PATH}.bak.${Date.now()}`;
    console.log(`[nginx] backup → ${backupPath}`);
    r = await run(conn, `cp ${NGINX_CONF_PATH} ${backupPath} && echo "backed up"`);
    console.log(r.stdout);
    if (r.code !== 0) { console.error('backup failed:', r.stderr); conn.end(); process.exit(1); }

    // Insert block trước dòng "location /" (root location)
    const SED_CMD = `sed -i '/    location \\/ {/i\\\n${NGINX_LOCATION_BLOCK.replace(/\n/g, '\\n').replace(/\$/g, '\\$')}\n' ${NGINX_CONF_PATH}`;
    console.log('[nginx] inserting location block...');
    r = await run(conn, SED_CMD);
    if (r.code !== 0) { console.error('sed failed:', r.stderr); conn.end(); process.exit(1); }
    r = await run(conn, 'nginx -t 2>&1');
    console.log(r.stdout);
    if (r.code !== 0) {
      console.error('nginx -t failed → restoring backup');
      await run(conn, `cp ${backupPath} ${NGINX_CONF_PATH}`);
      conn.end(); process.exit(1);
    }
    r = await run(conn, 'systemctl reload nginx && echo "reloaded"');
    console.log(r.stdout);
  }

  // 4) verify
  console.log('\n[verify] curl localhost:3011/healthz');
  r = await run(conn, 'curl -sS http://127.0.0.1:3011/healthz');
  console.log(r.stdout);
  console.log('\n[verify] curl https public /_vneid/healthz');
  r = await run(conn, 'curl -sS https://anticounterfeit.test9.io.vn/_vneid/healthz');
  console.log(r.stdout);
  console.log('\n[verify] pm2 list mock-vneid');
  r = await run(conn, 'pm2 list | grep mock-vneid');
  console.log(r.stdout);

  conn.end();
  console.log('\n[done]');
}

main().catch(e => { console.error(e); process.exit(1); });
