// Auto-generated by deploy_mock_vneid.js — DO NOT edit manually
module.exports = {
  apps: [{
    name: 'mock-vneid',
    script: 'server.js',
    cwd: '/var/www/mock-vneid',
    time: true,
    autorestart: true,
    max_memory_restart: '200M',
    env: {
      NODE_ENV: 'production',
      PORT: 3011,
      MOCK_VNEID_SECRET: '5b5921655526752d20d39cac512dd7678d7812b9b982842455392cf88523dbea',
      MOCK_VNEID_ISSUER: 'https://anticounterfeit.test9.io.vn/_vneid',
      MOCK_VNEID_PREFIX: '/_vneid',
    },
  }],
};
