name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'vntrust/package-lock.json'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./vntrust

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./vntrust

      - name: Build Next.js App
        run: npm run build
        working-directory: ./vntrust

      - name: Copy Files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "vntrust/.next,vntrust/public,vntrust/package.json,vntrust/package-lock.json,vntrust/next.config.ts,vntrust/next-env.d.ts,vntrust/tsconfig.json,vntrust/prisma,vntrust/postcss.config.mjs,vntrust/eslint.config.mjs,vntrust/src/generated"
          target: "/var/www/vntrust"
          strip_components: 1

      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/vntrust
            npm ci --production --legacy-peer-deps
            npx prisma generate
            pm2 restart vntrust || pm2 start npm --name "vntrust" -- start
            pm2 save
